GoogleForms/Shoppy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('products.urls', namespace='products')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GoogleForms/products/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from products.views import form_update, form_delete


urlpatterns = [
    url(r'^login/$', views.auth_login, name='authentication'),
    url(r'^logout$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^$', views.ProductList.as_view(), name='hello'),
    url(r'^product/(?P<pk>[0-9]+)/$', views.ProductDetail.as_view(), name='detail'),
    url(r'^product/new', views.new_product, name="new"),
    url(r'^update/(?P<id_form>\d+)/$', form_update, name="forms_update"),
    url(r'^Delete/(?P<id_form>\d+)/$', form_delete, name="form_delete"),
]

GoogleForms/products/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    User = models.ForeignKey(User, default="", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=250, default="")
    descripcion = models.CharField(max_length=255, default="")
    pregunta = models.CharField(max_length=255, default="")

    def __str__(self):
        return str(self.titulo) 
    class Meta:
        ordering = ('id',)

"""
class Question(models.Model):
    TitleForm = models.ForeignKey(Product, on_delete=models.CASCADE)
    question=models.CharField(max_length=250)
    

    def __str__(self):
        return self.question

    class Meta:
        ordering = ('id',)


class Answer(models.Model):
    formQuestion = models.ForeignKey(Question, default="", blank=False, on_delete=models.CASCADE)
    answer=models.CharField(max_length=250)
    

    def __str__(self):
        return self.answer

    class Meta:
        ordering = ('id',)

"""




"""
class Favorite(models.Model):
    user = models.ForeignKey(Client)
    product = models.ForeignKey(Product)

    class Meta:
        verbose_name = 'Favorite'
        verbose_name_plural = 'Favorites'

    def __str__(self):
        return '%s %s' % (self.user.name, self.product.name)
"""

GoogleForms/products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

GoogleForms/products/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.template import loader
from django.shortcuts import (
    render, 
    get_object_or_404, 
    redirect
)

from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

from django.views.generic import ListView
from django.views.generic.detail import DetailView

from .forms import ProductForm
from .models import Product
from .mixins import LoginRequiredMixin
from .forms import ProductForm


class ProductList(ListView):
    model = Product


class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product


@login_required()
def new_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            return HttpResponseRedirect('/')
    else:
        form = ProductForm()

    template = loader.get_template('new_product.html')
    context = {
        'form': form
    }
    return HttpResponse(template.render(context, request))


def auth_login(request):
    if request.method == 'POST':
        action = request.POST.get('action', None)
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        first_name = request.POST.get('first_name', None)
        last_name = request.POST.get('last_name', None)

        if action == 'signup':
            user = User.objects.create_user(username=username,
                                            password=password,
                                            last_name=last_name,
                                            first_name=first_name)
            user.save()
        elif action == 'login':
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
    context = {}
    return render(request, 'login/login.html', context)

#Funcion para Update para vistas basadas en funciones

def form_update(request, id_form):
        formulario = Product.objects.get(id=id_form)
        if request.method =='GET':
            form = ProductForm(instance=formulario)
        else:
            form= ProductForm(request.POST, instance=formulario)
            if form.is_valid():
                form.save()
            return redirect('/')
        return render(request,'new_product.html', {'form':form})


#funcion Delete para vistas basadas en funciones
def form_delete(request,id_form):
    formulario = Product.objects.get(id=id_form)
    if request.method =='POST':
        formulario.delete()
        return redirect('/')
    return render(request,'form_delete.html',{'formulario':formulario})

GoogleForms/templates/form_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
	<style>
        body{background-color: rgba(0, 0, 0, 0.808);
                color: white;
         }
        
        h3{color: yellow;}
        form,h1{text-align: center;}  

        
          
    </style>
    <meta charset="UTF-8">
    <title>Delete Form</title>
</head>
<body>
    <h1>Google Forms</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
	    <h3>¿Desea eliminar el registro?: {{ product.titulo }} </h3>
        <button type="submit">Eliminar</button>
        <a href="{% url "products:hello" %}">Cancelar</a>
    </form>  
    
</body>
</html>

GoogleForms/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body{
            background-image: url("../media/newform.jpg");
            }
        h1,h3{color: yellow; text-align: center;}
        form{text-align: center;}
        
    </style>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="action" value="login">

        <input type="text" name="username" placeholder="Usuario">
        <br><br>
        <input type="password" name="password" placeholder="password" ><br><br>

        <button type="submti">Ingresar</button>
    </form>
    <h3>¿No estas Registrado?</h3>
        <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="action" value="signup">
        <p>
        <input type="text" name="username"placeholder="Usuario">
        <input type="password" name="password"placeholder="password">
        </p>
        <p>
         <input type="text" name="first_name"placeholder="Nombre">
        <input type="text" name="last_name"placeholder="Apellido">
        </p>

        <button type="submti">Registrarse</button>
    </form>
</body>
</html>

GoogleForms/templates/new_product.html
<!DOCTYPE html>
<html lang="en">
<head>
	<style>
        body{
            background-image: url("media/newform.jpg");
            background-repeat: no-repeat;
            background-size: cover;
             
        }
        h1{
        	text-align: center;
        	color: yellow;
        }
        input{
        	text-align: center;
        }
        button{
        	background-color:#00FF00;
        	color: black;
        }

        table{
        	margin: auto;
        	text-align: right;
        }
        label{color: red;}
        
    </style>
    <meta charset="UTF-8">
    <title>New Form</title>
</head>
<body>
    <h1>Google Forms</h1>
    <table>
    	<tr>
    		<td>
    		 <form method="POST" enctype="multipart/form-data">
             {% csrf_token %}
	        {{ form.as_p }}
	        <button type="submit">Crear Formulario</button>
    		</form>
    		</td>
    	</tr>
    </table>
   
</body>
</html>

GoogleForms/templates/products/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ product.name }}</title>
    <style>
         body{background-color: rgba(0, 0, 0, 0.808);
                color: white;
         }
        h1{text-align: center;color: #00FF00}
        h3{color: yellow;}
        p{text-align: center;}
        table{margin:auto}
        ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: yellowgreen;
        }

        li {
        float: right;
        }

        li a {
        display: flex;
        color: white;
        text-align: center;
        padding: 8px 14px;
        text-decoration: none;
        }

        li a:hover {
        background-color: #111;
        }
    </style>  
</head>
<body >
        <ul>
                <li><a href="#about"> 
                    {% if user.is_authenticated %}{{ user.username }} </a>
                </li>
                <li>
                    <a href="{% url "products:logout" %}">Logout</a>
                        {% else %}
                            <a href="{% url "products:authentication" %}">login</a>
                        {% endif %}
                </li>
            </ul>
        <h1>Google Form: {{ product.titulo }}</h1>
    <table border="1">
        <thead>
            <td>ID</td>
            <td>Autor</td>
            <td>Titulo</td>
            <td>Descripcion</td>
            <td>Preguntas</td>
        </thead>
        <tbody>
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ product.titulo }}</td>
                <td>{{ product.descripcion }}</td>
                <td>
                    <ol>
                        <li>{{ product.pregunta }}</li>
                    </ol> 
                </td>
            </tr>
        </tbody>
    </table>
       
</body>
</html>

GoogleForms/templates/products/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GoogleForms</title>
    <style>
        body{
            background-image: url("media/newform.jpg");
            color:white; 
        }
        h1{text-align: center;
           color:#00FF00}
        h3{text-align: right;}
        h2{text-align: center;}
        a{color: yellowgreen;}
        p{color:#00FF00;}
        table{margin: auto;}
                ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: yellowgreen;
        }

        li {
        float: right;
        }

        li a {
        display: flex;
        color: white;
        text-align: center;
        padding: 8px 14px;
        text-decoration: none;
        }

        li a:hover {
        background-color: #111;
        }
    </style>
    
</head>
<body>
    <ul>
        <li><a href="#about"> 
            {% if user.is_authenticated %}{{ user.username }} </a>
        </li>
        <li>
            <a href="{% url "products:logout" %}">Logout</a>
                {% else %}
                    <a href="{% url "products:authentication" %}">login</a>
                {% endif %}
        </li>
    </ul>
         
        
    <h1>Google Forms</h1>
    <h2><a  href="{% url "products:new" %}">Crear Nuevo Formulario</a></h2>
    <table >
        <thead >
            <td>ID</td>
            <td>GoogleForm</td>
            <td>Descripcion</td>
            <td></td>
        </thead>
        <tbody>
        {% for pr in object_list %}
            <tr>
                <td>{{ pr.id }}</td>
                <td><a href="{% url "products:detail" pr.id %}">
                        {{ pr.titulo }}</a></td>
                <td>{{ pr.descripcion }}</td>
                <td>
                    <button><a href="{% url "products:forms_update" pr.id %}">Editar</a></button> 
                    <button><a href="{% url "products:form_delete" pr.id %}">Eliminar</a> </button>
                </td>          
            </tr>
        {% endfor %}
    </tbody>
    </table>

</body>
</html>